### ISSUE TITLE
create workflow module

### ISSUE THREAD

**Issue by jayyeras** [xebialabs/AWSWebinar#10]
Using "devops-as-code-demo", use PetClinic artifacts and templates to deploy app to Fargate using xl-release and xl-deploy.

Will need module, README.md and slides.

**Comment by deepu105** [comment]
This demo sample has been updated under AWSWebinar/xl-platform, please rename/move the folder as required for your flow. We used the rest-o-rant application instead of pet clinic, I guess it should be ok. It also includes a Readme

**Comment by deepu105** [comment]
Also we are working to add a git trigger and Jenkins build stage to the XLR pipeline for this, let me know if you think that is not necessary

**Comment by jayyeras** [comment]
@deepu105 Thanks for working on this. Yes please add the git trigger and jenkins build stage to the XLR pipeline.

**Comment by deepu105** [comment]
@jayyeras we have added the jenkins build and git trigger in a branch here https://github.com/xebialabs/AWSWebinar/tree/xlr-with-git-trigger/modules/xebialabs/devops-as-code
It has become more complicated due to the build steps, there are few issues that we need to iron out. Will hopefully get everything working by tomorrow

**Comment by jayyeras** [comment]
@deepu105 thank you for adding these. however, we need to add this to the existing modules. would it help if we jump on a quick call and i can explain?

@tbuntel thoughts? my concern is that replacing the existing modules with the full demo will not work for the webinar.
